ci(codeql): set continue-on-error until Code Scanning enabled in repo settings
CodeQL Analysis fails on all PRs because Code Scanning is not enabled
on this private repository. Setting continue-on-error: true so that
the CI check does not block PR merges. Enable Code Scanning in:
GitHub > Settings > Security > Code Scanning

Error: 'Code scanning is not enabled for this repository'
See: https://docs.github.com/code-security/code-scanning/enabling-code-scanning/configuring-default-setup-for-code-scanning